### ISSUE TITLE
could not debug contract created by contract

### ISSUE THREAD

**Issue by slepher** [trufflesuite/truffle-debugger#37] opened 2018-03-06 08:48 UTC
project: https://github.com/slepher/truffle_test

truffle version: v4.1.0

reproduce:
`truffle develop`
`migrate`
`StorageManager.deployed().then((instance) => {return instance.createStorage()});`
`debug <txid>`

> [ slepher@issac ~/project/truffle_test (master) ] truffle develop
> Connected to existing Truffle Develop session at http://localhost:9545/
> 
> truffle(develop)> migrate
> Compiling ./contracts/Migrations.sol...
> Compiling ./contracts/SimpleStorage.sol...
> Compiling ./contracts/StorageManager.sol...
> Writing artifacts to ./build/contracts
> 
> Using network 'develop'.
> 
> Running migration: 1_initial_migration.js
>   Deploying Migrations...
>   ... 0xbb145925d2348100bcaca3ed4782c6e65fe010c71525367609e57df64f77aabf
>   Migrations: 0x9efec315e368e8812025b85b399a69513cd0e716
> Saving successful migration to network...
>   ... 0x834bf7895ffbaa129edd5925cae516d4966677bfebc1568dc56fc1ca9018e1a0
> Saving artifacts...
> Running migration: 2_deploy_storage.js
>   Deploying StorageManager...
>   ... 0x9e1b3f5d67b91bb44a8ecc4223ad2be114cb1d6e6719cb17d7c3ec6baa933a36
>   StorageManager: 0xd5e8aa91bda51688e6f3de82e52fb38e35298515
>   Deploying SimpleStorage...
>   ... 0xcf719e6cfc842b2680e2ef347e94014d380703bbed7503e18c7109ed940a8d0f
>   SimpleStorage: 0xa509542ada3196a38bd6fd03b253547ee09220c4
> Saving successful migration to network...
>   ... 0x2b63a20cb4c69f0caa8d9abcb5e2859058fd9b346333a9f684c959a2d3ce7619
> Saving artifacts...
> truffle(develop)> StorageManager.deployed().then((instance) => {return instance.createStorage()});
> { tx: '0xf5775c50c8b3bfdc449a3cff765aa2cc78e325e887ba047939a836d84e985372',
>   receipt:
>    { transactionHash: '0xf5775c50c8b3bfdc449a3cff765aa2cc78e325e887ba047939a836d84e985372',
>      transactionIndex: 0,
>      blockHash: '0xaff312633613d4cdd6904281f81156c12cc03e2f65e31f23d429a2ad20fe169a',
>      blockNumber: 65,
>      gasUsed: 201088,
>      cumulativeGasUsed: 201088,
>      contractAddress: null,
>      logs: [],
>      status: '0x01',
>      logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000' },
>   logs: [] }
> truffle(develop)> debug 0xf5775c50c8b3bfdc449a3cff765aa2cc78e325e887ba047939a836d84e985372
> 
> Gathering transaction data...
> 
> Addresses affected:
>  0x96738907596faa777927b47dd8ce1a385fa8ebb4 - SimpleStorage
>  0xd5e8aa91bda51688e6f3de82e52fb38e35298515 - StorageManager
> 
> Commands:
> (enter) last command entered (step next)
> (o) step over, (i) step into, (u) step out, (n) step next
> (;) step instruction, (p) print instruction, (h) print this help, (q) quit
> (b) toggle breakpoint, (c) continue until breakpoint
> (+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
> (?) list existing watch expressions
> (v) print variables and values, (:) evaluate expression - see `v`
> 
> 
> StorageManager.sol:
> 
> 3: import "./SimpleStorage.sol";
> 4:
> 5: contract StorageManager {
>    ^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> debug(develop:0xf5775c50...)> o
> 
> StorageManager.sol:
> 
>  9:   uint public afterCounter;
> 10:
> 11:   function createStorage() public returns(uint) {
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> debug(develop:0xf5775c50...)> o
> 
> StorageManager.sol:
> 
> 10:
> 11:   function createStorage() public returns(uint) {
> 12:       counter = counter + 1;
>                               ^
> 
> debug(develop:0xf5775c50...)> o
> 
> StorageManager.sol:
> 
> 11:   function createStorage() public returns(uint) {
> 12:       counter = counter + 1;
> 13:       simple = new SimpleStorage();
>                    ^^^^^^^^^^^^^^^^^^^
> 
> debug(develop:0xf5775c50...)> o
> redux-saga error: uncaught at saga
> at saga
>  at saga
>  at takeEvery
>  at tickSaga
>  TypeError: Cannot convert undefined or null to object
>     at entries (<anonymous>)
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-debugger/dist/debugger.js:1835:52
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:76:1
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:90:1
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:698:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:699:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:699:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:699:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:699:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:699:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at proc (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:270:1)
>     at runForkEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:554:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
> 
> SimpleStorage.sol:
> 
> 1: pragma solidity ^0.4.18;
> 2:
> 3: contract SimpleStorage {
>    ^^^^^^^^^^^^^^^^^^^^^^^^
> 
> debug(develop:0xf5775c50...)>

**Comment by gnidan** [comment] 2018-03-06 17:54
Ah, thanks for identifying this missing use case. Will hopefully have this fixed soon!

**Comment by gnidan** [comment] 2018-03-08 15:25
This might be fixed in Truffle v4.1.3. Please try again and let me know!

**Comment by slepher** [comment] 2018-03-08 16:34
it works,
but fails on other testcase

project updated: https://github.com/slepher/truffle_test

truffle version: v4.1.3

reproduce:
truffle develop
migrate
StorageManager.deployed().then((instance) => {return instance.createAnotherStorage(10)});
debug <txid>
> truffle(develop)> StorageManager.deployed().then((instance) => {return instance.createAnotherStorage(10)});
> { tx: '0x1c5d811a00645270468001e41f0b37c3aa2f60227e245fcc9d5d3e9064ed4733',
>   receipt:
>    { transactionHash: '0x1c5d811a00645270468001e41f0b37c3aa2f60227e245fcc9d5d3e9064ed4733',
>      transactionIndex: 0,
>      blockHash: '0x418d4d4f7ff68f050be9f51b2b2cc3669e58b8eab19fac688fac50078737e78c',
>      blockNumber: 17,
>      gasUsed: 158960,
>      cumulativeGasUsed: 158960,
>      contractAddress: null,
>      logs: [],
>      status: '0x01',
>      logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000' },
>   logs: [] }
> truffle(develop)> debug 0x1c5d811a00645270468001e41f0b37c3aa2f60227e245fcc9d5d3e9064ed4733
> 
> Gathering transaction data...
> 
> Addresses affected:
>  0x5db1a375e62abf9e569241617479c44d2d07ae6a - AnotherStorage
>  0xdda6327139485221633a1fcd65f4ac932e60a2e1 - StorageManager
> 
> Commands:
> (enter) last command entered (step next)
> (o) step over, (i) step into, (u) step out, (n) step next
> (;) step instruction, (p) print instruction, (h) print this help, (q) quit
> (b) toggle breakpoint, (c) continue until breakpoint
> (+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
> (?) list existing watch expressions
> (v) print variables and values, (:) evaluate expression - see `v`
> 
> 
> StorageManager.sol:
> 
> 4: import "./AnotherStorage.sol";
> 5:
> 6: contract StorageManager {
>    ^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> debug(develop:0x1c5d811a...)> o
> 
> StorageManager.sol:
> 
> 15:   }
> 16:
> 17:   function createAnotherStorage(uint initData) public returns(uint) {
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> debug(develop:0x1c5d811a...)> o
> 
> StorageManager.sol:
> 
> 16:
> 17:   function createAnotherStorage(uint initData) public returns(uint) {
> 18:       another = new AnotherStorage(initData);
>                                        ^^^^^^^^
> 
> debug(develop:0x1c5d811a...)> o
> redux-saga error: uncaught at saga
> at saga
>  at saga
>  at stepOver
>  TypeError: Cannot read property 'binary' of undefined
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:891:1
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:76:1
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:90:1
>     at Function.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
>     at args (/usr/local/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:171:1)
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
>     at Function.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
>     at args (/usr/local/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:171:1)
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
>     at Function.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
>     at args (/usr/local/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:171:1)
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:698:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
>     at takeCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:466:1)
>     at Object.put (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/channel.js:73:1)
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/channel.js:161:1
>     at Array.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/channel.js:182:1)
>     at Object.emit (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/channel.js:26:1)
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/middleware.js:67:1
>     at dispatch (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux/es/applyMiddleware.js:35:1)
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/utils.js:250:1
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:489:1
>     at exec (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/scheduler.js:19:1)
>     at flush (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/scheduler.js:60:1)
>     at asap (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/scheduler.js:33:1)
>     at Array.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/channel.js:185:1)
>     at Object.emit (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/channel.js:26:1)
>     at Object.dispatch (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/middleware.js:67:1)
>     at Session.dispatch (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:2330:1)
> TypeError: Cannot read property 'source' of undefined
>     at TTY.onread (net.js:599:20)
>     at ReadStream.Readable.push (_stream_readable.js:213:10)
>     at readableAddChunk (_stream_readable.js:256:11)
>     at addChunk (_stream_readable.js:269:12)
>     at ReadStream.emit (events.js:160:13)
>     at ReadStream.onData (readline.js:1020:36)
>     at emitKeys.next (<anonymous>)
>     at emitKeys (internal/readline.js:420:14)
>     at ReadStream.emit (events.js:160:13)
>     at ReadStream.onkeypress (readline.js:165:10)
>     at REPLServer.self._ttyWrite (repl.js:566:7)
>     at REPLServer.Interface._ttyWrite (readline.js:920:14)
>     at REPLServer.Interface._line (readline.js:640:8)
>     at REPLServer.Interface._onLine (readline.js:287:10)
>     at REPLServer.emit (events.js:160:13)
>     at REPLServer.onLine (repl.js:497:10)
>     at REPLServer.runBound [as eval] (domain.js:383:12)
>     at bound (domain.js:370:14)
>     at ReplManager.interpret (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/lib/repl.js:119:1)
>     at Object.interpreter (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/lib/commands/debug.js:399:1)

**Comment by gnidan** [comment] 2018-03-10 00:16
Thanks for the convenient reproduction steps @slepher!

**Comment by slepher** [comment] 2018-03-26 13:58
how to use truffle-debugger's newest version which fixed this bug.

**Comment by gnidan** [comment] 2018-03-29 05:08
@slepher upgrade to Truffle v4.1.3, although I'm not sure that'll fix the problem completely. Should have a release with more fixes in the next few days.

**Comment by qbit86** [comment] 2018-03-30 15:27
Have the same issue:
```
$ truffle version
Truffle v4.1.5 (core: 4.1.5)
Solidity v0.4.21 (solc-js)
```
Ganache 1.1.0
```
$ truffle debug 0xae9714e73fb556e9fbf61493d872539123c37d986436256b0ff8a36371f532cc
...
Gathering transaction data...

redux-saga error: uncaught at session.saga
at session.saga
 TypeError: Cannot read property 'binary' of undefined
```

Is there any workaround?

**Comment by gnidan** [comment] 2018-03-30 15:32
Oh I just noticed that bug also. I think it has to do with the change in solc version; try running your migrations and transaction again with this version.

**Comment by qbit86** [comment] 2018-03-30 15:45
> again with this version.

With which version?

I remove `build/contracts/`, restart Ganache GUI, execute `truffle migrate` (it recompiles all with latest version of `solc-js`). Then do some actions with deployed contract in my web-interface (some successful, some not), receive `txHash` and pass it to `truffle debug`. Same result: “TypeError: Cannot read property 'binary' of undefined”.

**Comment by gnidan** [comment] 2018-03-30 16:02
> With which version?

(with Truffle v4.1.5)

Rats, that's annoying. Any chance your code is public so I could reproduce?

**Comment by qbit86** [comment] 2018-03-31 11:03
> Any chance your code is public so I could reproduce?

It's not public (hosted in closed Git-repo on Bitbucket), but I guess I could share repro privately. Probably, after weekends.

**Comment by qbit86** [comment] 2018-04-02 15:32
> Any chance your code is public so I could reproduce?

I temporarily uploaded archive here: <https://mega.nz/#!B1AxWTJZ!FdCEZPlDMgWJ62CEbM5K2lzY-f2zaQD-0tTKnUUdrJY>

1. In folder `bps-smart-contracts/` execute `npm install`
2. In file `.env` specify the same test mnemonic as you use in Ganache GUI, for example:
```
MNEMONIC="candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
```

To receive undebuggable transaction I execute `WombatErc721Token.testCatchWombat(...)` (successfully), then `Erc721Auction.startAuction(0, 1, 2)` (failure). There is also `BpsReact2` project where you can try to call these contract methods from web-interface via MetaMask/Custom RPC, buttons Catch and Sell(0, 1, 2).

**Comment by gnidan** [comment] 2018-04-02 17:37
@qbit86 I downloaded the repo if you want to remove it for privacy reasons. I'll get to reproducing this later tonight or tomorrow. Thanks!

**Comment by gnidan** [comment] 2018-04-03 17:55
@qbit86 I'm not able to reproduce the error you reported. I found a couple other uncaught exceptions, however, so I'm going to make those fail more gracefully. Not sure the root of it, will have to look more thoroughly. If you have any additional information, that would be most helpful! Thanks!

**Comment by sebamatusr** [comment] 2018-04-05 23:12
I am having the exact same issue with the same solc and truffle version. Did you find a workaround for this?

**Comment by gnidan** [comment] 2018-04-05 23:28
So I found this problem and it's hairy. I don't know a workaround right now. I'll reopen this issue until I can get back to it and do some issue maintenance (since the problem here isn't OP)

**Comment by gnidan** [comment] 2018-04-06 17:12
Actually re-closing. Issue #51 has been created for this issue specifically. Please comment there for issues related to this missing `binary`. Thanks!

**Closed by gnidan** 2018-04-06 17:12 UTC
