### ISSUE TITLE
RangeError: Invalid typed array length error for any variable after somepoint

### ISSUE THREAD

**Issue by vladyslav2** [trufflesuite/truffle-debugger#74] opened 2018-05-19 22:19 UTC
Arch Linux \r (\l)

Truffle v4.1.8 (core: 4.1.8)
Solidity v0.4.23 (solc-js)

Working with timestamp and arrays (basically trying to save timestamps for they addresses)
After any arrays calls debug stops showing any variable information with an error:

```debug(develop:0x70b1a332...)> v
RangeError: Invalid typed array length: 5.620462069890859e+47
    at /usr/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
    at args (/usr/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:209:1)
    at Function.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:90:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:76:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:2202:50
    at Array.map (<anonymous>)
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:2207:50
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:2080:1
    at decode (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:4508:1)
    at decodeMemoryReference (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:4333:1)
    at decodeValue (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:4284:1)
    at read (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:4277:1)
    at Object.readBytes (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:4577:1)
    at new Uint8Array (native)
    at typedArrayConstructByLength (<anonymous>)
```

Even for uint variable (its been working few lines before)
```
debug(develop:0x70b1a332...)> :_timestamp
RangeError: Invalid typed array length: 5.620462069890859e+47
    at /usr/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
    at args (/usr/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:209:1)
    at Function.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:90:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:76:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:2202:50
    at Array.map (<anonymous>)
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:2207:50
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:2080:1
    at decode (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:4508:1)
    at decodeMemoryReference (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:4333:1)
    at decodeValue (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:4284:1)
    at read (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:4277:1)
    at Object.readBytes (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-debugger/dist/debugger.js:4577:1)
    at new Uint8Array (native)
    at typedArrayConstructByLength (<anonymous>)
```

Tried to do migrate --reset, truffle migrate --reset --compile-all did not help

**Comment by vladyslav2** [comment] 2018-05-19 22:56
My problem somehow connected with mappings `mapping (address => uint256)` and `block.timestamp` 
combination of this breaks variables output for the whole contract.
But output for other contracts will still work.

**Comment by vladyslav2** [comment] 2018-05-19 23:40
Solved an issue by creating a function:

```
  function getTimestamp() internal view returns(uint256) {
    return block.timestamp + 1;
  }
```

and using it instead of direct `block.timestamp`

Solved the issue

**Comment by gnidan** [comment] 2018-05-22 15:49
Ah, @vladyslav2, since you have a workaround, I'm closing this as duplicate of #30 

Thanks for bringing this to my attention!

**Closed as completed by gnidan** 2018-05-22 15:49 UTC
